[package]
edition = "2021"
name = "pain2wash"
version = "0.1.0"

[dependencies]
axum = "0.6.3"
color-eyre = "0.6.2"
reqwest = { version = "0.11.14", default-features = false, features = ["brotli", "cookies", "deflate", "gzip", "json", "rustls-tls", "multipart", "trust-dns"] }
tokio = { version = "1.24.2", features = ["full"] }
