app = "pain2wash"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[deploy]
strategy = "canary"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 250
soft_limit = 200
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["http", "tls"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
grace_period = "5s"
interval = "10s"
method = "get"
path = "/health"
protocol = "http"
restart_limit = 0
timeout = "2s"
tls_skip_verify = false
