app = "pain2wash-influx"
kill_signal = "SIGINT"
kill_timeout = 5

[mounts]
source="influx_data"
destination="/var/lib/influxdb2"

[env]

[[services]]
http_checks = []
internal_port = 8086
protocol = "tcp"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["http", "tls"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
