{
 "title": "Pay2Wash Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Location Code",
    "query": {
     "query": "label_values(machine_updated, location)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "# Location Codes\n\n- **89**: Phillips Bedrijfschool"
   }
  },
  {
   "title": "Drier Statuses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_reserved{location=\"$location\", name=~\"D.+\"} + on (name) (2 * machine_running{location=\"$location\"}) + on (name) (4 * machine_in_maintenance{location=\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Washer Statuses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_reserved{location=\"$location\", name=~\"W.+\"} + on (name) (2 * machine_running{location=\"$location\"}) + on (name) (4 * machine_in_maintenance{location=\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Drier Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_remaining_time{location=\"$location\", name=~\"D.*\"} - ((machine_running{location=\"$location\"} == bool 0) * 3601)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remaining Washer Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_remaining_time{location=\"$location\", name=~\"W.*\"} - ((machine_running{location=\"$location\"} == bool 0) * 3601)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(machine_updated) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_updated{location=\"$location\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drier Statuses",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 10 },
   "targets": [
    {
     "expr": "clamp_min(floor(log2(machine_reserved{location=\"$location\", name=~\"D.+\"} + on (location, name) (2 * machine_running) + on (location, name) (4 * machine_in_maintenance))), -1) + 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Update Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 / rate(sum by (location) (machine_updated{location=\"$location\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Token",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_user_token{location=\"$location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Washer Statuses",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 17 },
   "targets": [
    {
     "expr": "clamp_min(floor(log2(machine_reserved{location=\"$location\", name=~\"W.+\"} + on (location, name) (2 * machine_running) + on (location, name) (4 * machine_in_maintenance))), -1) + 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Verbose", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Controller Logic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max by(name) (machine_controller_logic{location=\"$location\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Gateway Offline",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "max by (name) (machine_gateway_offline{location=\"$location\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "User Token",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (location) (machine_user_token{location=\"$location\"})"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "max by (location) (machine_updated{location=\"$location\"} * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Maintenance",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "max by (name) (machine_in_maintenance{location=\"$location\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reserved",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "max by (name) (machine_reserved{location=\"$location\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Running",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "max by (name) (machine_running{location=\"$location\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remaining Time Is from Machine",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "max by (name) (machine_remaining_time_is_from_machine{location=\"$location\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reserver",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (name) (machine_reserver{location=\"$location\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Starter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (name) (machine_starter{location=\"$location\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remaining Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (name) (machine_remaining_time{location=\"$location\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Calculated Machine Statuses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "machine_reserved{location=\"$location\"} + on (location, name) (2 * machine_running) + on (location, name) (4 * machine_in_maintenance)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}